version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_nest_app
    environment:
      POSTGRES_DB: nestDb
      POSTGRES_USER: nestUser
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: