import { EspecialidadDoctors } from "../components/register/enum/enums";

export const especialidadesArray: string[] = [
    EspecialidadDoctors.ALERGIA_E_INMUNOLOGIA,
    EspecialidadDoctors.ANATOMIA_PATOLOGICA,
    EspecialidadDoctors.ANESTESIOLOGIA,
    EspecialidadDoctors.CARDIOLOGIA,
    EspecialidadDoctors.CIRUGIA_CARDIOVASCULAR,
    EspecialidadDoctors.CIRUGIA_GENERAL,
    EspecialidadDoctors.CIRUGIA_PEDIATRICA,
    EspecialidadDoctors.CLINICA_MEDICA,
    EspecialidadDoctors.DERMATOLOGIA,
    EspecialidadDoctors.DIAGNOSTICO_POR_IMAGEN,
    EspecialidadDoctors.ERMETOLOGIA,
    EspecialidadDoctors.ENDOCRINOLOGIA,
    EspecialidadDoctors.FISIATRIA,
    EspecialidadDoctors.GASTROENTEROLOGIA,
    EspecialidadDoctors.GERIATRIA,
    EspecialidadDoctors.HEMATOLOGIA,
    EspecialidadDoctors.HEMOTERAPIA,
    EspecialidadDoctors.INFECTOLOGIA,
    EspecialidadDoctors.INMUNOLOGIA,
    EspecialidadDoctors.MEDICINA_GENERAL,
    EspecialidadDoctors.NEFROLOGIA,
    EspecialidadDoctors.NEUMONOLOGIA,
    EspecialidadDoctors.NEUROLOGIA,
    EspecialidadDoctors.OFTALMOLOGIA,
    EspecialidadDoctors.ONCOLOGIA,
    EspecialidadDoctors.ORTOPEDIA_Y_TRAUMATOLOGIA,
    EspecialidadDoctors.PEDIATRIA,
    EspecialidadDoctors.OTORRINOLARINGOLOGIA,
    EspecialidadDoctors.REUMATOLOGIA,
    EspecialidadDoctors.SALUD_MENTAL_PSIQUIATRIA,
    EspecialidadDoctors.TERAPIA_INTENSIVA_DE_ADULTOS,
    EspecialidadDoctors.TOCOGINECOLOGIA,
    EspecialidadDoctors.UROLOGIA,
    EspecialidadDoctors.GENERAL
];