export enum EspecialidadDoctors {
    ALERGIA_E_INMUNOLOGIA = 'Alergia e Inmunologia',
    ANATOMIA_PATOLOGICA = 'Anatomia Patologica',
    ANESTESIOLOGIA = 'Anestesiologia',
    CARDIOLOGIA = 'Cardiologia',
    CIRUGIA_CARDIOVASCULAR = 'Cirugia Cardiovascular',
    CIRUGIA_GENERAL = 'Cirugia General',
    CIRUGIA_PEDIATRICA = 'Cirugia Pediatrica',
    CLINICA_MEDICA = 'Clinica Medica',
    DERMATOLOGIA = 'Dermatologia',
    DIAGNOSTICO_POR_IMAGEN = 'Diagnostico por Imagines',
    ERMETOLOGIA = 'Ermetologia',
    ENDOCRINOLOGIA = 'Endocrinologia',
    FISIATRIA = 'Fisiatria',
    GASTROENTEROLOGIA = 'Gastroenterologia',
    GERIATRIA = 'Geriatria',
    HEMATOLOGIA = 'Hematologia',
    HEMOTERAPIA = 'Hemoterapia',
    INFECTOLOGIA = 'Infectologia',
    INMUNOLOGIA = 'Inmonoliga',
    MEDICINA_GENERAL = 'Medicina General',
    NEFROLOGIA = 'Nefrologia',
    NEUMONOLOGIA = 'Neumonologia',
    NEUROLOGIA = 'Neurologia',
    OFTALMOLOGIA = 'Oftalmologia',
    ONCOLOGIA = 'Oncologia',
    ORTOPEDIA_Y_TRAUMATOLOGIA = 'Ortopedia y Traumatologia',
    PEDIATRIA = 'Pediatria',
    OTORRINOLARINGOLOGIA = 'Otorrinolaringologia',
    REUMATOLOGIA = 'Reumatologia',
    SALUD_MENTAL_PSIQUIATRIA = 'Salud Mental - Psiquiatria',
    TERAPIA_INTENSIVA_DE_ADULTOS = 'Terapia Intensiva de Adultos',
    TOCOGINECOLOGIA = 'Tocoginecologia',
    UROLOGIA = 'Urologia',
    GENERAL = 'General'
  }

export enum userOrDoc {
    admin = 'admin',
    user = 'user',
    doctor = 'doctor'
}
